version: "3.7"
services:

  nginx:
    image: nginx:latest
    volumes:
        - ./nginx:/etc/nginx
    depends_on:
      - app      
      - pb
    ports:
      - "80:80"

  app:
    image: node:20-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 8080:8040
    working_dir: /app
    depends_on:
      - pb
    volumes:
      - ./:/app:rw
  pb:
    image: spectado/pocketbase:latest
    ports:
      - 8090:80
    volumes:
    - ./bend/pb_data:/pb_data:Z  












